name: Update Status GIF

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow rebasing

      - name: Get UTC hour
        id: time
        run: |
          CURRENT_UTC_HOUR=$(date -u +"%H")
          echo "CURRENT_UTC_HOUR=$CURRENT_UTC_HOUR" >> $GITHUB_ENV

      - name: Determine GIF file
        run: |
          if [ ${{ env.CURRENT_UTC_HOUR }} -ge 7 ] && [ ${{ env.CURRENT_UTC_HOUR }} -lt 16 ]; then
            echo "GIF_FILE=active.gif" >> $GITHUB_ENV
          else
            echo "GIF_FILE=passive.gif" >> $GITHUB_ENV
          fi

      - name: Update README.md
        run: |
          sed -i "s|\(<img align=\"right\" alt=\"status-gif\".*src=\"\).*\.gif\(\".*\)|\1$GIF_FILE\2|" README.md

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: ${{ steps.check-changes.outputs.has_changes == 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore: Auto-update status GIF to $GIF_FILE"
          # Pull latest changes and rebase to avoid conflicts
          git pull --rebase origin main
          git push origin main
