name: Update Status GIF

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get UTC hour
        id: time
        run: |
          echo "CURRENT_UTC_HOUR=$(date -u +'%H')" >> $GITHUB_ENV

      - name: Set GIF file
        run: |
          if [ ${{ env.CURRENT_UTC_HOUR }} -ge 7 ] && [ ${{ env.CURRENT_UTC_HOUR }} -lt 16 ]; then
            echo "GIF_FILE=active.gif" >> $GITHUB_ENV
          else
            echo "GIF_FILE=passive.gif" >> $GITHUB_ENV
          fi

      - name: Update README.md
        run: |
          sed -i "s|src=\".*\.gif\"|src=\"https://github.com/oliviaisntcringe/oliviaisntcringe/blob/main/$GIF_FILE\"|" README.md

      - name: Check for changes
        id: check-changes
        run: |
          echo "has_changes=$(git status --porcelain | grep -q '.' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: ${{ steps.check-changes.outputs.has_changes == 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore: Auto-update status GIF to $GIF_FILE"
          git push
